tasks:
    - before: echo before
      init: >
         echo init &&
         echo init2
      command: echo command
    - before: echo before
      init: echo init
      command: echo command
      openMode: split-right
